spring:
  application:
    name: spring-boot-docker
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    initialization-mode: always
    username: sa
    password:
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always

